### ISSUE TITLE
ac 9560 iwlwifi-9000-pu-b0-jf-b0-43.ucode

### ISSUE THREAD

**Issue by sealyau** [wkennington/linux-firmware#4]
Hi,
I seem to be having a connection stability issue with the above config, dns takes a long time to resolv and rsync will not connect to remote locations, after a period it times out. I'm a bit of a newb but know my way around the terminal fairly well, unsure of what log files would possibly shed some light though if someone can point me in the right direction?

Thanks

**Comment by wkennington** [comment]
I don't actually maintain these firmware images, they come from distributed sources and originate at https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git
